/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 테이블 tour.ARTICLE_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `ARTICLE_INFO` (
  `ART_IDX` int(11) NOT NULL AUTO_INCREMENT COMMENT '글 일련번호',
  `ART_TITLE` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '글 제목',
  `ART_THUM_URL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '대표사진 썸네일 URL 경로',
  `ART_AMOUNT` int(11) DEFAULT NULL COMMENT '필요 경비(예상)',
  `ART_AVAIL_DAY` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '가능한 요일 (YYYYMMDD)',
  `ART_AVAIL_FROM_TIME` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '가능한 시작시간(HHMM)',
  `ART_AVAIL_TO_TIME` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '가능한 종료시간(HHMM)',
  `ART_SHORT_DESC` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '글 축약 설명',
  `ART_DESC` text COLLATE utf8mb4_unicode_ci COMMENT '글 설명',
  `ART_REG_DATE` datetime NOT NULL COMMENT '글 등록일자',
  PRIMARY KEY (`ART_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='컨텐츠 메인 정보 ';

-- 테이블 데이터 tour.ARTICLE_INFO:~0 rows (대략적) 내보내기syssysmysqlmysqlinnodbcomeet
/*!40000 ALTER TABLE `ARTICLE_INFO` DISABLE KEYS */;
INSERT INTO `ARTICLE_INFO` (`ART_IDX`, `ART_TITLE`, `ART_THUM_URL`, `ART_AMOUNT`, `ART_AVAIL_DAY`, `ART_AVAIL_FROM_TIME`, `ART_AVAIL_TO_TIME`, `ART_SHORT_DESC`, `ART_DESC`, `ART_REG_DATE`) VALUES
	(2ARTICLE_INFOARTICLE_PLACE_INFO, '글 제목', NULL, NULL, NULL, NULL, NULL, NULL, '', '0000-00-00 00:00:00');
/*!40000 ALTER TABLE `ARTICLE_INFO` ENABLE KEYS */;

-- 테이블 tour.ARTICLE_PLACE_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `ARTICLE_PLACE_INFO` (
  `ART_IDX` int(11) NOT NULL COMMENT '글 일련번호 (FK)',
  `PLACE_IDX` int(11) NOT NULL COMMENT '여행장소 일련번호 (FK)',
  PRIMARY KEY (`ART_IDX`,`PLACE_IDX`),
  KEY `FK_ARTICLE_PLACE_INFO_PLACE_INFO` (`PLACE_IDX`),
  CONSTRAINT `FK_ARTICLE_PLACE_INFO_ARTICLE_INFO` FOREIGN KEY (`ART_IDX`) REFERENCES `ARTICLE_INFO` (`ART_IDX`) ON DELETE CASCADE,
  CONSTRAINT `FK_ARTICLE_PLACE_INFO_PLACE_INFO` FOREIGN KEY (`PLACE_IDX`) REFERENCES `PLACE_INFO` (`PLACE_IDX`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='해당 글의 여행장소 정보관리';

-- 테이블 데이터 tour.ARTICLE_PLACE_INFO:~0 rows (대략적) 내보내기
/*!40000 ALTER TABLE `ARTICLE_PLACE_INFO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ARTICLE_PLACE_INFO` ENABLE KEYS */;

-- 테이블 tour.ARTICLE_THEME_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `ARTICLE_THEME_INFO` (
  `ART_IDX` int(11) NOT NULL COMMENT '글 일련번호 (FK)',
  `THEME_IDX` int(11) NOT NULL COMMENT '여행테마 일련번호 (FK)',
  PRIMARY KEY (`ART_IDX`,`THEME_IDX`),
  KEY `FK_ARTICLE_THEME_INFO_THEME_INFO` (`THEME_IDX`),
  CONSTRAINT `FK_ARTICLE_THEME_INFO_ARTICLE_INFO` FOREIGN KEY (`ART_IDX`) REFERENCES `ARTICLE_INFO` (`ART_IDX`) ON DELETE CASCADE,
  CONSTRAINT `FK_ARTICLE_THEME_INFO_THEME_INFO` FOREIGN KEY (`THEME_IDX`) REFERENCES `THEME_INFO` (`THEME_IDX`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='해당 글의 여행테마 관리';

-- 테이블 데이터 tour.ARTICLE_THEME_INFO:~0 rows (대략적) 내보내기
/*!40000 ALTER TABLE `ARTICLE_THEME_INFO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ARTICLE_THEME_INFO` ENABLE KEYS */;

-- 테이블 tour.AUTH_CODE_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `AUTH_CODE_INFO` (
  `AUTH_EMAIL` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '이메일주소',
  `AUTH_CODE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '인증번호',
  `AUTH_REG_DATE` datetime NOT NULL COMMENT '인증번호 생성일자',
  PRIMARY KEY (`AUTH_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='인증번호 발송 관리 테이블\r\n';

-- 테이블 데이터 tour.AUTH_CODE_INFO:~0 rows (대략적) 내보내기
/*!40000 ALTER TABLE `AUTH_CODE_INFO` DISABLE KEYS */;
/*!40000 ALTER TABLE `AUTH_CODE_INFO` ENABLE KEYS */;

-- 테이블 tour.KEYWORD_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `KEYWORD_INFO` (
  `KEYWORD_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '키워드 단어',
  `KEYWORD_COUNT` int(11) NOT NULL COMMENT '카운트 수',
  `KEYWORD_REG_DATE` datetime NOT NULL COMMENT '키워드 등록일자',
  PRIMARY KEY (`KEYWORD_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='크롤링 키워드 단어관리';

-- 테이블 데이터 tour.KEYWORD_INFO:~0 rows (대략적) 내보내기
/*!40000 ALTER TABLE `KEYWORD_INFO` DISABLE KEYS */;
/*!40000 ALTER TABLE `KEYWORD_INFO` ENABLE KEYS */;

-- 테이블 tour.MEMBER_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `MEMBER_INFO` (
  `MBR_EMAIL` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '이메일주소',
  `MBR_NAME` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '이름',
  `MBR_PWD` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '패스워드',
  `MBR_REG_DATE` datetime NOT NULL COMMENT '등록일자',
  PRIMARY KEY (`MBR_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='가입자 정보';

-- 테이블 데이터 tour.MEMBER_INFO:~0 rows (대략적) 내보내기
/*!40000 ALTER TABLE `MEMBER_INFO` DISABLE KEYS */;
/*!40000 ALTER TABLE `MEMBER_INFO` ENABLE KEYS */;

-- 테이블 tour.PLACE_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `PLACE_INFO` (
  `PLACE_IDX` int(11) NOT NULL AUTO_INCREMENT COMMENT '여행장소 일련번호',
  `PLACE_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '여행장소 이름',
  `PLACE_USE_YN` varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '여행장소 사용여부(''Y'', ''N'')',
  `PLACE_REG_DATE` datetime NOT NULL COMMENT '여행장소 등록일자',
  PRIMARY KEY (`PLACE_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='여행장소 관리 테이블';

-- 테이블 데이터 tour.PLACE_INFO:~2 rows (대략적) 내보내기
/*!40000 ALTER TABLE `PLACE_INFO` DISABLE KEYS */;
INSERT INTO `PLACE_INFO` (`PLACE_IDX`, `PLACE_NAME`, `PLACE_USE_YN`, `PLACE_REG_DATE`) VALUES
	(1, '홍대', 'Y', '2019-04-20 17:55:14'),
	(2, '건대', 'Y', '2019-04-20 17:55:23');
/*!40000 ALTER TABLE `PLACE_INFO` ENABLE KEYS */;

-- 테이블 tour.THEME_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `THEME_INFO` (
  `THEME_IDX` int(11) NOT NULL AUTO_INCREMENT COMMENT '여행테마 일련번호',
  `THEME_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '여행테마 이름',
  `THEME_USE_YN` varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '여행테마 사용여부(''Y'', ''N'')',
  `THEME_REG_DATE` datetime NOT NULL COMMENT '여행테마 등록일자',
  PRIMARY KEY (`THEME_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=' 테마 관리 테이블\r\n';

-- 테이블 데이터 tour.THEME_INFO:~2 rows (대략적) 내보내기
/*!40000 ALTER TABLE `THEME_INFO` DISABLE KEYS */;
INSERT INTO `THEME_INFO` (`THEME_IDX`, `THEME_NAME`, `THEME_USE_YN`, `THEME_REG_DATE`) VALUES
	(2, '히든플레이스', 'Y', '2019-04-20 17:54:20'),
	(3, '로컬 맛집 투어', 'Y', '2019-04-20 17:54:31');
/*!40000 ALTER TABLE `THEME_INFO` ENABLE KEYS */;

-- 테이블 tour.NEWS_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `NEWS_INFO` (
  `NEWS_IDX` int(11) NOT NULL AUTO_INCREMENT COMMENT '뉴스 일련번호',
  `NEWS_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '뉴스 제목',
  `NEWS_URL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '뉴스 URL 경로',
  `NEWS_REG_DATE` datetime NOT NULL COMMENT '뉴스 등록일자',
  PRIMARY KEY (`NEWS_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='크롤링 키워드 단어관리';

-- 테이블 데이터 tour.NEWS_INFO:~2 rows (대략적) 내보내기
/*!40000 ALTER TABLE `NEWS_INFO` DISABLE KEYS */;
INSERT INTO 'NEWS_INFO' ('NEWS_IDX', 'NEWS_URL', 'NEWS_REG_DATE') VALUES
    (1, NULL, '2019-05-05 18:50:10'),
    (2, NULL, '2019-05-06 12:12:12');
/*!40000 ALTER TABLE `NEWS_INFO` ENABLE KEYS */;


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
